language: java
dist: trusty
sudo: true
jdk: oraclejdk11
addons:
  sonarcloud:
    organization: "dionrats-github"
  apt:
    packages:
      - oracle-java8-installer
before_install:
    - cd university-agent
services:
  - 'docker'
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=Dionrats_StudyBits -Dsonar.organization=dionrats-github -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_TOKEN
after_success:
  - if [ branch == master ]; then
      mvn dockerfile:build && \
      docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD && \
      docker push drats/university-agent && \
      docker logout
    fi
