version: '3'
services:

  pool:
    image: studybits/indy-pool:0.1.2
    ports:
    - "9701-9708:9701-9708"
    environment:
      TEST_POOL_IP: $POOL_IP
    networks:
      - studybits
      - groningen
      - gent

  rug-university-agent:
    image: drats/university-agent
    ports:
      - 8080:8080
    environment:
      nl.quintor.studybits.university.pool: $POOL_IP
      nl.quintor.studybits.university.name: Rijksuniversiteit Groningen
      spring.datasource.url: jdbc:mysql://rug_db/agents
      spring.datasource.password: RijksuniversiteitGroningen
      IPFS.node.host: rug_ipfs
    networks:
      - groningen
    depends_on:
      - pool
      - rug_db
      - rug_ipfs

  gent-university-agent:
    image: drats/university-agent
    ports:
      - 8081:8080
    environment:
      nl.quintor.studybits.university.pool: $POOL_IP
      nl.quintor.studybits.university.name: Universiteit Gent
      spring.datasource.url: jdbc:mysql://gent_db/agents
      spring.datasource.password: UniversiteitGent
      IPFS.node.host: gent_ipfs
    networks:
      - gent
    depends_on:
     - pool
     - gent_db
     - gent_ipfs

  rug_db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: RijksuniversiteitGroningen
      MYSQL_DATABASE: agents
    networks: 
      - groningen

  gent_db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: UniversiteitGent
      MYSQL_DATABASE: agents
    networks: 
      - gent
    
  rug_ipfs:
    image: ipfs/go-ipfs
    ports:
      - 5001:5001
    networks:
      - studybits
      - groningen

  gent_ipfs:
    image: ipfs/go-ipfs
    ports:
      - 5002:5001
    networks:
      - studybits
      - gent

  seeder:
    image: drats/seeder
    command: ["./wait-for-it.sh", "-t", "100", "rug-university-agent:8080", "--", "bash", "seed.sh"]
    environment:
      TEST_POOL_IP: $POOL_IP
      GRONINGEN_IP: rug-university-agent
      GENT_IP: gent-university-agent
    networks:
      - studybits
      - groningen
      - gent
    depends_on:
     - pool
     - rug-university-agent
     - gent-university-agent

networks:
  studybits:
    driver: bridge
  groningen:
    driver: bridge
  gent:
    driver: bridge
