version: '2.1'
services:
  quindy:
    image: quindy
    build: ./quindy
    command: sh -c 'sleep 3000; exit 0'
  pool:
    build:
      context: ci
      dockerfile: indy-pool.dockerfile
      args:
        pool_ip: $TEST_POOL_IP
    ports:
    - "9701-9708:9701-9708"
    # Host networking is used, because we need to know the pool IP at build time, which is kind-of tricky
    network_mode: "host"

  university-agent-rug:
    build:
      context: university-agent
    command: mvn package spring-boot:run
    network_mode: "host"
    environment:
    - TEST_POOL_IP=$TEST_POOL_IP
    - SPRING_PROFILES_ACTIVE=mobile-test
    - NL_QUINTOR_STUDYBITS_UNIVERSITY_NAME=Rijksuniversiteit Groningen
    depends_on:
      quindy:
        condition: service_started
      pool:
        condition: service_started
      university-agent-gent:
        condition: service_healthy

    healthcheck:
      test: curl -f http://localhost:8080/swagger-ui.html || exit 1
      interval: 5s
      timeout: 2s
      retries: 35
  university-agent-gent:
    build:
      context: university-agent
    command: mvn package spring-boot:run
    network_mode: "host"
    environment:
    - TEST_POOL_IP=$TEST_POOL_IP
    - NL_QUINTOR_STUDYBITS_UNIVERSITY_NAME=Universiteit Gent
    - SERVER_PORT=8081
    - SPRING_PROFILES_ACTIVE=mobile-test
    depends_on:
      quindy:
        condition: service_started
      pool:
        condition: service_started
    healthcheck:
      test: curl -f http://localhost:8081/swagger-ui.html || exit 1
      interval: 5s
      timeout: 2s
      retries: 35
  tests:
    build:
      context: university-agent
    environment:
    - TEST_POOL_IP=$TEST_POOL_IP
    network_mode: "host"
    command: mvn verify
    depends_on:
      university-agent-rug:
        condition: service_healthy

