version: '2.3'
services:
  pool:
    image: registry.quintor.nl/studybits_pool
    network_mode: "host"

  backend-university:
    depends_on:
      - pool
    build:
      context: university
    network_mode: "host"
    healthcheck:
      test: curl -f http://localhost:8090/test/health || exit 1
      interval: 5s
      timeout: 2s
      retries: 35

  backend-student:
    depends_on:
      backend-university:
        condition: service_healthy
    build:
      context: student
    network_mode: "host"
    healthcheck:
      test: curl -f http://localhost:8095/test/health || exit 1
      interval: 5s
      timeout: 2s
      retries: 35

  tests:
    build:
      context: integration-tests
    network_mode: "host"
    depends_on:
      backend-student:
        condition: service_healthy
      backend-university:
        condition: service_healthy

#  frontend-student:
#    build:
#      context: ../StudyBits-Frontend/student
#    network_mode: "host"