version: '2.3'
services:
  pool:
    build:
      context: ../ci
      dockerfile: indy-pool.dockerfile
    ports:
    - "9701-9708:9701-9708"
    # Host networking is used, because we need to know the pool IP at build time, which is kind-of tricky
    network_mode: "host"

  jars:
    depends_on:
      - pool
    build:
      context: ../

  backend-student:
    depends_on:
      - jars
    build:
      context: ../studybits-student
      args:
        LIBINDY_VERSION: ${LIBINDY_VERSION}
    ports:
    - "8090:8090"
    network_mode: "host"

  backend-university:
    depends_on:
      - jars
    build:
      context: ../studybits-university
      args:
        LIBINDY_VERSION: ${LIBINDY_VERSION}
    ports:
      - "8095:8095"
    network_mode: "host"
