version: '2.3'
services:
  wrapper:
    build:
      context: ../studybits-student
      args:
        LIBINDY_VERSION: ${LIBINDY_VERSION}
    network_mode: "host"
  pool:
    build:
      context: ../ci
      dockerfile: indy-pool.dockerfile
    ports:
    - "9701-9708:9701-9708"
    # Host networking is used, because we need to know the pool IP at build time, which is kind-of tricky
    network_mode: "host"
