version: '2.3'
services:
  wrapper:
    build:
      context: .
    network_mode: "host"
  pool:
    image: registry.quintor.nl/studybits_pool
    ports:
    - "9701-9708:9701-9708"
    # Host networking is used, because we need to know the pool IP at build time, which is kind-of tricky
    network_mode: "host"